"""empty message

Revision ID: 726000db9fc8
Revises: 58b896a161fd
Create Date: 2020-09-07 00:05:06.848198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726000db9fc8'
down_revision = '58b896a161fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venue_id_fkey', 'Show', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
